<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>035f2041-712a-41a8-93a6-5c706167a09a</elementGuidId>
    <imagePath></imagePath>
    <name>div_fileUploadInstructions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.MuiBox-root &gt; div:nth-child(2) &gt; div:nth-child(2) &gt; div:nth-child(3) &gt; div</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>