<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>317c6d40-cafd-468a-b210-ef03cbd123c6</elementGuidId>
    <imagePath></imagePath>
    <name>button_sloweyCongChung</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'slowey cong chung
            
            tạo bởi Regular User
            
            Đang xử lý
            
            Lĩnh vực:
            
            Lĩnh vực công chứng Sao y chứng thực
            
            Dịch vụ:
            
            Chứng thực bản sao từ bản chính
            
            U
            
            S
            
            Đã kết thúc')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.MuiPaper-root &gt; .MuiButtonBase-root</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>slowey cong chung
        
        tạo bởi Regular User
        
        Đang xử lý
        
        Lĩnh vực:
        
        Lĩnh vực công chứng Sao y chứng thực
        
        Dịch vụ:
        
        Chứng thực bản sao từ bản chính
        
        U
        
        S
        
        Đã kết thúc</value>
        <webElementGuid>bb104204-858f-40f6-93f2-b4e67278b865</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>bb104204-858f-40f6-93f2-b4e67278b865</webElementGuid>
    </webElementProperties>
</WebElementEntity>