<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0a906444-3587-4941-950b-2a0b27df97bc</elementGuidId>
    <imagePath></imagePath>
    <name>button_arrowBack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'ArrowBackIcon')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(3) &gt; div &gt; div &gt; div &gt; div &gt; .MuiButtonBase-root</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>ArrowBackIcon</value>
        <webElementGuid>07fd4749-9ab6-46a7-81ff-da839f42b489</webElementGuid>
    </webElementProperties>
</WebElementEntity>