<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa3a1c32-69c3-4aec-abc9-d417a7c8efb6</elementGuidId>
    <imagePath></imagePath>
    <name>div_uploadFile</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/button[1]/div[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'DriveFolderUploadRoundedIcon')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:has-text=/^K\u00e9o v\u00e0 th\u1ea3 ho\u1eb7c ch\u1ecdn t\u1ec7p\u0110\u1ecbnh d\u1ea1ng: pdf, doc, docx$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>DriveFolderUploadRoundedIcon</value>
        <webElementGuid>07fd4749-9ab6-46a7-81ff-da839f42b489</webElementGuid>
    </webElementProperties>
</WebElementEntity>