<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6b1c0af2-4113-438d-a76c-3aa224887841</elementGuidId>
    <imagePath></imagePath>
    <name>p_statusIndicators</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/span[1]/span[2]/span[1]/p[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(${p_statusIndicators_divNthChild}) &gt; .MuiStepLabel-root &gt; .MuiStepLabel-labelContainer &gt; .MuiStepLabel-label &gt; .MuiTypography-root</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>