<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bde30300-b79f-46d1-b019-7ab92aa4b818</elementGuidId>
    <imagePath></imagePath>
    <name>button_requestDemo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Yêu cầu demo')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Y\u00eau c\u1ea7u demo\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Yêu cầu demo</value>
        <webElementGuid>0746614d-fcdb-4914-9a0f-9bbbddcfa573</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>0746614d-fcdb-4914-9a0f-9bbbddcfa573</webElementGuid>
    </webElementProperties>
</WebElementEntity>