<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dbd824c0-6918-4dc5-bb74-2602c11ae5a3</elementGuidId>
    <imagePath></imagePath>
    <name>button_createNotarySession</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'slowey cong chung
            
            tạo bởi Regular User
            
            Đang xử lý
            
            Lĩnh vực:
            
            Lĩnh vực công chứng Sao y chứng thực
            
            Dịch vụ:
            
            Chứng thực bản sao từ bản chính
            
            U
            
            S
            
            Đã kết thúc')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.MuiPaper-root &gt; .MuiButtonBase-root</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>slowey cong chung
        
        tạo bởi Regular User
        
        Đang xử lý
        
        Lĩnh vực:
        
        Lĩnh vực công chứng Sao y chứng thực
        
        Dịch vụ:
        
        Chứng thực bản sao từ bản chính
        
        U
        
        S
        
        Đã kết thúc</value>
        <webElementGuid>07fd4749-9ab6-46a7-81ff-da839f42b489</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>07fd4749-9ab6-46a7-81ff-da839f42b489</webElementGuid>
    </webElementProperties>
</WebElementEntity>