<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>85188208-f8f1-44e3-9a1f-d969f660a992</elementGuidId>
    <imagePath></imagePath>
    <name>button_next_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[7]/div[2]/button[2]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'ArrowCircleRightRoundedIcon')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button:nth-child(4) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>ArrowCircleRightRoundedIcon</value>
        <webElementGuid>0746614d-fcdb-4914-9a0f-9bbbddcfa573</webElementGuid>
    </webElementProperties>
</WebElementEntity>