<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7ad6ee72-c88a-47e2-9154-eabb5714e2c5</elementGuidId>
    <imagePath></imagePath>
    <name>item_selectFromMachine</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/ul[1]/li[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.MuiPaper-root &gt; .MuiList-root &gt; li &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>